version: '3'

services:
  backend:
    build: ./backend
    working_dir: /backend
    command: npm run web
    volumes:
      - ./frontend:/frontend
      - ./backend:/backend

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/:rw
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest

    profiles:
      - donotstart

    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  postgres:
    image: postgres:14-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nfcuser
      - POSTGRES_PASSWORD=nfcpass
      - POSTGRES_DB=nfcattendance
